name: pokedex_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: 7.0.0
  cupertino_icons: ^1.0.8
  http: 1.5.0
  json_serializable: 6.11.1
  build_runner: 2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  -assets/fonts
  -assets/images

font:
  -family: Roboto
  fonts:
    fonts:
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 900
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Roboto-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Roboto-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Roboto-BlackItalic.ttf
        weight: 900
        style: italic